services:
  backend:
    container_name: pipe_backend
    build:
      context: .
      dockerfile: Dockerfile
    command: bash /app/local_entrypoint.sh
    ports:
      - "8010:8010"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/back_static
      - media_volume:/app/back_media
    depends_on:
      - pipe_db

  pipe_db:
    container_name: pipe_postgres
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${POSTGRES_TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
